language: android

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

# Prevent Travis from running automatic project install.
install:
  - true

script:
  - ci/build.sh

cache:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
